name=input("Enter your name ")
age=input("Enter your age ")
height=input("Enter your height ")
weight=input("Enter your weight ")
print(f"Your name is {name} age is {age}, weight is {weight} and height is {height}")
